### ISSUE TITLE
建议：考虑将header带出来吗？

### ISSUE THREAD

**Issue by zhoubangfu** [anncwb/vite-plugin-mock#10]
有一部分需求需要用到header，建议将header一并带到response入参中

**Comment by anncwb** [comment]
可以给个例子？

**Comment by zhoubangfu** [comment]
比如登录后的请求将token放到header中，模拟接口想根据两个不同token判断不同的身份？

**Comment by zhoubangfu** [comment]
像这里一样：
https://github.com/zhoubangfu/vue3-admin/blob/master/mock/login.ts#L44

**Comment by anncwb** [comment]
升级2.4.0
