### ISSUE TITLE
不支持 mock 目录下的多个子目录

### ISSUE THREAD

**Issue by qinghuanI** [anncwb/vite-plugin-mock#11]
我有这样的需求：

```sh

mock/
   clients/
     client.ts
   groups/
      group.ts
      

```

我设置 mockPath 为 'mock' 或 'mock/**/*' 均不能生效

@anncwb

**Comment by anncwb** [comment]
mockPath 使用默认 mock即可。我在examples测试了的你用例，没出现你的问题。你可以尝试下吗？ @qinghuanI

**Comment by anncwb** [comment]
或者你将examples内的用例改成你的，提供个最小复现github仓库给我

**Comment by qinghuanI** [comment]
> mockPath 使用默认 mock即可。我在examples测试了的你用例，没出现你的问题。你可以尝试下吗？ @qinghuanI

嗯，我找到原因了，谢谢
