### ISSUE TITLE
生产环境下获取不到headers

### ISSUE THREAD

**Issue by hsiangleev** [anncwb/vite-plugin-mock#15]
请问为什么开发环境下可以拿到headers，生产环境下没有，可以在生产环境拿到headers吗

**Comment by xiaoxian521** [comment]
mockjs拦截了ajax请求，通过服务开启的mock是可以在network中看到请求的，生产环境下是直接创建mock数据看不到请求，这本身就是mockjs的特性，并不是bug吧

**Comment by anncwb** [comment]
是的，确认了下，生产环境拿不到headers和restful接口的参数

**Comment by hsiangleev** [comment]
@xiaoxian521 没有说是bug，我的意思是能不能加一个功能可以让生产环境获取headers
