### ISSUE TITLE
请求404，且 TypeScript sample的例子报错 Binding element 'query' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by yinzixie** [anncwb/vite-plugin-mock#19]
vite.config.ts
![image](https://user-images.githubusercontent.com/48106713/113686800-02a90d80-970b-11eb-8d3c-eacd03dd4832.png)

HelloWord.vue
![image](https://user-images.githubusercontent.com/48106713/113687027-3f750480-970b-11eb-8ceb-aa699270d4b4.png)

mock/map.ts
![image](https://user-images.githubusercontent.com/48106713/113687643-e8236400-970b-11eb-9934-02aed22503a7.png)

Binding element 'query' implicitly has an 'any' type.

求教。照着sample写的， 根本没法用啊。

我把 query 这个参数删掉后，然后用axios请求，直接404。大佬快救救孩子吧。
![image](https://user-images.githubusercontent.com/48106713/113687129-5ca9d300-970b-11eb-91bd-49f045fa52fd.png)

**Comment by xiaoxian521** [comment]
map.ts文件中的url中的api是你在项目中配置的代理地址吗 如果是改成{url:'/map'}试试

**Comment by yinzixie** [comment]
没有设置代理，事实上我把axios.get 换成 fetch 后显示可以请求，但是返回的东西并不是我定义的东西。

**Comment by xiaoxian521** [comment]
嗯嗯 方便的话给个仓库链接我帮你调试下

**Comment by yinzixie** [comment]
感谢，可能哪里没写对，麻烦你了。

https://github.com/yinzixie/test

**Comment by xiaoxian521** [comment]
嗯嗯 我看了一下 你的mock目录需要放在与public平级目录下哦

**Comment by yinzixie** [comment]
啊，真的是。解决了。感谢。

**Comment by starlet0822** [comment]
> 嗯嗯 方便的话给个仓库链接我帮你调试下
大佬 我也遇到这个问题 方便帮忙看下么
