### ISSUE TITLE
使用DELETE+Params的格式，请求404

### ISSUE THREAD

**Issue by WilenChen** [anncwb/vite-plugin-mock#21]
mock配置如下：
![image](https://user-images.githubusercontent.com/12603891/115354660-74458900-a1ec-11eb-8c7a-24256b8ab17d.png)

请求代码如下：
![image](https://user-images.githubusercontent.com/12603891/115354917-bbcc1500-a1ec-11eb-81e8-05ed554e9d84.png)

请求结果如下：
![image](https://user-images.githubusercontent.com/12603891/115354986-ce464e80-a1ec-11eb-8233-fa7fbaa5cdb2.png)

如果把参数放在data中，mock正常：
![image](https://user-images.githubusercontent.com/12603891/115355125-f33ac180-a1ec-11eb-9a23-ea27669e8084.png)
![image](https://user-images.githubusercontent.com/12603891/115355174-fd5cc000-a1ec-11eb-9541-c52d7c111098.png)

**Comment by anncwb** [comment]
可以先用post代替，我有时间排查下

**Comment by anncwb** [comment]
closed  in 4cb55f8
