### ISSUE TITLE
TypeError: Cannot read property '.ts' of undefined

### ISSUE THREAD

**Issue by van-chin** [anncwb/vite-plugin-mock#22]
![image](https://user-images.githubusercontent.com/61791214/119449709-88d5ed80-bd65-11eb-97ff-790e3943ac38.png)

报错如上图 是 mockPath 参数 设置有问题么？

**Comment by ralfsqual** [comment]
这个问题我也遇到了 目前退回了2.5.0。    貌似是2.5.2中有个地方回去取__require.extensions[xxxx],   这个__require是个function。   __require.extensions必然是个undefined。

**Comment by van-chin** [comment]
> 这个问题我也遇到了 目前退回了2.5.0。 貌似是2.5.2中有个地方回去取__require.extensions[xxxx], 这个__require是个function。 __require.extensions必然是个undefined。

指定 `mockPath ` 对当前文件的 相对路径 可以让错误消失

**Comment by anncwb** [comment]
可以暂时还原回2.5.0

**Comment by van-chin** [comment]
@anncwb 2.5.3 已经解决此问题了哇 我更新到2.5.3 没有错误了也可以正常 进行mock  👍
