### ISSUE TITLE
配置了prodserver，打包项目放在 nginx 上，访问接口报错 not found

### ISSUE THREAD

**Issue by now915** [anncwb/vite-plugin-mock#28]
按照 readme 进行配置mock，prodServer，放在 src 目录下的，本地调试正常能访问接口并且返回 mock 的数据，但是打包放在 nginx 上访问接口时报错，not found.
![Uploading image.png…]()
according to  readme.md file, I configed mock and prodServer, put it under src. Then I run my project in development mode, it goes well, and the interfaces returned normal mock data, but It run error in production environment。
The production environment is local nginx environment ? I don't konw why? plz help me...

**Comment by anncwb** [comment]
能给我一个复现仓库吗

**Comment by now915** [comment]
> 能给我一个复现仓库吗

感谢！
https://github.com/now915/eslint-prettier.git

**Comment by anncwb** [comment]
两个错误
- 你项目是js的，默认是支持ts的，所以你需要设置`supportTs=true`
- mockProdServer 这个文件命名不一样，你的项目应该是`mockProServer`

```ts
 viteMockServe({
        mockPath: 'mockPlugin',
        supportTs: false,
        localEnabled: command === 'serve',
        prodEnabled: command !== 'serve' && prodMock,
        //  这样可以控制关闭mock的时候不让mock打包到最终代码内
        injectCode: `
          import { setupProdMockServer } from './mockProServer';
          setupProdMockServer();
        `,
      }),
```

**Comment by now915** [comment]
非常感谢~
