### ISSUE TITLE
多页应用没有src/main.js的话会报错

### ISSUE THREAD

**Issue by mideng2** [anncwb/vite-plugin-mock#33]
vite-plugin-vue-mock need to set the entry file.

为什么一定要有这个文件呢？

**Comment by anncwb** [comment]
这个是为了在生产环境用到的时候，注入代码。可以提供一个复现示例给我下

**Comment by PlayGuitar-CoderQ** [comment]
那我用react 怎么办？？ main.tsx   而源码只对 'ts', 'js' 做判断

**Comment by anncwb** [comment]
升级到2.9.0，然后可以自行配置 injectFile

```
injectFile: path.join(xxxx)
```
