### ISSUE TITLE
升级到2.9.0后报错

### ISSUE THREAD

**Issue by hooray** [anncwb/vite-plugin-mock#34]
报错内容是 `mock reload error TypeError: Cannot read property '.js' of undefined`

我尝试使用仓库内的 `js-example` ，手动安装 vite-plugin-mock 并替换 vite.config.js 里的 `import { viteMockServe } from 'vite-plugin-mock';` ，也会有一样的问题

**Comment by anncwb** [comment]
升级到2.9.1

**Comment by JettyFlutter3306** [comment]
我在本地使用 vite-plugin-mock 但是引用了公司的二方库，然后显示 mock reload error Error: Cannot find package  'D:\EnterpriseProjects\HMSCorePushCampaignWebsite\code\node_modules\@hw-appgallery\push-adapter\package.json' imported from D:\EnterpriseProjects\HMSCorePushCampaignWebsite\code\src\mocks\metadata\_index.bundled_1724896460419_jve3g56shsd.mjs 这是什么情况？假如没有在mock代码里面引入这个二方库就不会报错。
