### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by WilenChen** [anncwb/vite-plugin-mock#8]
[vite:mock] mock reload error TypeError: esbuild.startService is not a function

**Comment by anncwb** [comment]
我这边测试都是可以的,可以给个复现示例?或者尝试在项目examples内复现

**Comment by WilenChen** [comment]
ts-example 可以复现

node -v
v12.6.0

npm -v
6.9.0

**Comment by anncwb** [comment]
尝试将vite版本固定到2.0.5  2.1.0之后的版本有问题

**Comment by songzhenze** [comment]
因为项目中依赖的 "rollup-plugin-esbuild": "^2.6.1" 插件代码中包含 esbuild.startService() 方法，但是 esbuild 已经移除了 esbuild.startService() 方法，导致了报错，升级 rollup-plugin-esbuild 插件可以解决。
![image](https://user-images.githubusercontent.com/50448175/111777193-eecd7100-88ed-11eb-9550-15b987205663.png)
![image](https://user-images.githubusercontent.com/50448175/111777346-22100000-88ee-11eb-838a-01bbed8c9243.png)

https://github.com/evanw/esbuild/blob/237870fbbf529fbefe4db069e21663be38c32373/CHANGELOG.md
![image](https://user-images.githubusercontent.com/50448175/111777026-ad3cc600-88ed-11eb-9b6c-ec0730320f0b.png)

**Comment by anncwb** [comment]
升级到2.3.0修复
