### ISSUE TITLE
文档中控制`injectCode`的值是不是写错了。

### ISSUE THREAD

**Issue by VXiaoXin** [anncwb/vite-plugin-mock#9]
文档中说当`localEnabled=true`时注入`injectCode`。

我用`VbenAdmin`的原代码试了很多种情况。
关于`localEnabled`、`prodEnabled`、`injectCode`的功能得出的结果：
- `localEnabled`控制mock开发环境是否启动。
- 如果生产环境想要使用`mock`，只有`prodEnabled`为true，`injectCode`注入指定代码时才会生效。

如此，更像是`prodEnabled`控制`injectCode`的注入。似乎和`localEnabled`没有什么关系。

这里困惑了很久，所以想问一下，是不是上面说的这样的呀。

**Comment by anncwb** [comment]
抱歉  可能文档写错了。应该是localEnabled=true时才生效。这个主要是为了在未开启mock时候，移除mock.js在最终的打包代码内

**Comment by ctt8520** [comment]
Vue: Object literal may only specify known properties, and localEnabled does not exist in type ViteMockOptions

**Comment by ctt8520** [comment]
检测viteMockServe 对象没有 prodEnabled和localEnabled 属性我也看了一下在类型定义中确实没有这两个 所以怎么能让他过检测不报红  --- 0.0


Vue: Object literal may only specify known properties, and localEnabled does not exist in type ViteMockOptions
